### ISSUE TITLE
Need source labeling

### ISSUE THREAD

**Issue by dcode** [spartan782/pcap-2-bro#1]
You should provide a command line argument to allow specifying a source identifier using the `ROCK::sensor_id` variable. This way it will be labelled correctly when it gets put into Kafka, allowing the analyst to query that specific data. If the user doesn't provide one, a random value should be used (perhaps a random UUID).

Also...you should use new Python format strings ;-)

You'll need to add the logic for the source parameter, but you could change the command string like so:
```
# Line 103
 command = '{} -C -r {} local "ROCK::sensor_id={}"'.format(bro_path, pcap, source)
```

**Comment by spartan782** [comment]
I can add that. If they don't provide one wouldn't it use the sensor_id that is stored in the config and look like the rest of the traffic that is being ingested? Is the reason for using a Random UUID to just be able to separate traffic from the normal flow?

**Comment by spartan782** [comment]
Source Field has been added. Uses UUID4 to generate a Source if none was provided.
